import { useEffect, useRef, useState } from 'react';
import { AgentRun, AgentRunCreate, AgentRunResult, KnowledgeBase, RagSearchHit, api } from '../api/client';
import { workbench } from '../api/workbench';
import { useWorkspace } from '../components/WorkspaceContext';
import { BrandProfile,BusinessBrief,ContentWorkflow,brandsApi } from '../api/brands';
import '../styles/brands.css';
import EvidenceProvenance from '../components/EvidenceProvenance';
import { EvidenceScope } from '../api/evidence';
import { useAvailableModels } from '../components/useAvailableModels';
import ModelTraceDetails from '../components/ModelTraceDetails';
interface Props {onOpenEvidence?:(id:number,scope?:EvidenceScope)=>void;onNavigate:(page:string)=>void;onOpenDraft?:(draftId:number,topicId:number|null,runId:number)=>void;initialRunId?:number|null;initialKnowledgeBaseId?:number;initialBrandId?:number|null;initialWorkflow?:string|null}
const labels:Record<string,string>={pending:'等待开始',running:'正在生成',completed:'已完成',skipped:'已跳过',failed:'执行失败',awaiting_review:'等待你审核',approved:'审核通过',rejected:'需要修改',cancelled:'已取消'};
export default function AgentWorkbenchPage({onOpenEvidence,onNavigate,onOpenDraft,initialRunId,initialKnowledgeBaseId,initialBrandId,initialWorkflow}:Props){
  const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  const {canWrite,canReview}=useWorkspace();const {models,modelsError}=useAvailableModels();
  const [form,setForm]=useState<AgentRunCreate>({goal:'',brand_profile_id:initialBrandId??null,workflow_key:(['knowledge_post','product_faq','case_story'].includes(initialWorkflow||'')?initialWorkflow:'knowledge_post') as ContentWorkflow['key'],mode:'inspiration',research_depth:'quick',target_audience:'',viewpoint:'只使用资料支持的事实，缺少依据时明确说明',personal_case:'',content_type:'auto',source_urls:[],provider:'local',model:'',auto_score:true,use_rag:true,knowledge_base_id:initialKnowledgeBaseId??null,rag_top_k:5,rag_min_score:.08});
  const [brands,setBrands]=useState<BrandProfile[]>([]);const [workflows,setWorkflows]=useState<ContentWorkflow[]>([]);const [briefReady,setBriefReady]=useState(false);const [downloading,setDownloading]=useState(false);
  const [requiredModel,setRequiredModel]=useState('');const [requiredParameters,setRequiredParameters]=useState('');
  const [knowledgeBases,setKnowledgeBases]=useState<KnowledgeBase[]>([]);const [sourceUrls,setSourceUrls]=useState('');const [run,setRun]=useState<AgentRunResult|null>(null);const [history,setHistory]=useState<AgentRun[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [historyError,setHistoryError]=useState('');const [pollError,setPollError]=useState('');const [reviewNote,setReviewNote]=useState('');const [showComposer,setShowComposer]=useState(!initialRunId);
  const modelInitialized=useRef(false);
  useEffect(()=>{if(!models.length||!briefReady||modelInitialized.current)return;modelInitialized.current=true;setForm(old=>({...old,provider:brands.find(b=>b.id===old.brand_profile_id)?.data_policy==='local_only'?'local':(models.find(item=>item.is_default)||models.find(item=>item.provider==='local')||models[0]).provider}));},[models,briefReady,brands]);
  useEffect(()=>{let active=true;Promise.all([brandsApi.list(),brandsApi.workflows()]).then(([items,templates])=>{if(!active)return;setBrands(items);setWorkflows(templates);setBriefReady(true);if(initialBrandId){const brand=items.find(b=>b.id===initialBrandId&&b.is_active);if(!brand){setError('指定品牌不可用或已归档，请重新选择。');setBriefReady(false);}else setForm(old=>({...old,brand_profile_id:brand.id,knowledge_base_id:brand.knowledge_base_id,workspace_id:brand.workspace_id,provider:brand.data_policy==='local_only'?'local':old.provider}));}}).catch(e=>{if(active)setError(`内容模板读取失败：${e.message}`);});return()=>{active=false;};},[]);
  const selectedBrand=brands.find(b=>b.id===form.brand_profile_id);
  const selectedWorkflow=workflows.find(w=>w.key===form.workflow_key);
  const selectBrand=(id:number|null)=>{const brand=brands.find(b=>b.id===id&&b.is_active);setForm(old=>({...old,brand_profile_id:brand?.id||null,knowledge_base_id:brand?.knowledge_base_id||old.knowledge_base_id,workspace_id:brand?.workspace_id,provider:brand?.data_policy==='local_only'?'local':old.provider,use_rag:true}));setBriefReady(true);};
  const downloadDelivery=async()=>{if(!run||downloading)return;setDownloading(true);setError('');try{const data=await brandsApi.delivery(run.id);if(!alive.current)return;const url=URL.createObjectURL(new Blob([data.markdown],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`交付清单-任务${run.id}.md`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'交付清单下载失败');}finally{setDownloading(false);}};
  const loadHistory=()=>{api.listAgentRuns(12).then(items=>{if(!alive.current)return;setHistory(items);setHistoryError('');}).catch(()=>{if(alive.current)setHistoryError('暂时无法读取最近任务。');});};
  useEffect(()=>{loadHistory();let active=true;api.listKnowledgeBases().then(items=>{if(!active)return;setKnowledgeBases(items);if(initialKnowledgeBaseId&&!items.some(item=>item.id===initialKnowledgeBaseId)){setError('指定知识库不可用，请重新选择。');setForm(old=>({...old,knowledge_base_id:null}));}else if(items[0])setForm(old=>({...old,knowledge_base_id:old.knowledge_base_id||items[0].id}));}).catch(()=>{if(active)setError('知识库列表读取失败，请刷新重试。');});return()=>{active=false;};},[]);
  useEffect(()=>{if(!initialRunId)return;let active=true;setLoading(true);api.getAgentRun(initialRunId).then(value=>{if(active)setRun(value);}).catch(e=>{if(active)setError(`无法读取指定任务：${e.message}`);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[initialRunId]);
  useEffect(()=>{if(!run||!['pending','running'].includes(run.status))return;let stopped=false,inflight=false;const id=run.id;const timer=window.setInterval(async()=>{if(inflight)return;inflight=true;try{const next=await api.getAgentRun(id);if(!stopped){setRun(next);setPollError('');if(!['pending','running'].includes(next.status))loadHistory();}}catch{if(!stopped)setPollError('连接暂时中断，正在重新读取进度。任务可能仍在执行，请不要重复创建。');}finally{inflight=false;}},1500);return()=>{stopped=true;window.clearInterval(timer);};},[run?.id,run?.status]);
  const action=async(fn:()=>Promise<AgentRunResult>)=>{setLoading(true);setError('');try{const next=await fn();if(!alive.current)return;setRun(next);if(next.id!==initialRunId)onNavigate(`agent?run=${next.id}`);setShowComposer(false);setReviewNote('');loadHistory();}catch(e){setError(e instanceof Error?e.message:'操作失败，请稍后重试。');}finally{setLoading(false);}};
  const start=()=>{if(!form.goal.trim())return;
    const parameters=[...new Set(requiredParameters.split(/\n+/).map(item=>item.trim()).filter(Boolean))];
    if(Boolean(requiredModel.trim())!==Boolean(parameters.length)){setError('填写必需参数时，请同时填写品牌及产品型号、至少一个参数名。');return;}
    if(parameters.length>10){setError('每次最多核对 10 个必需参数。');return;}
    if(parameters.length&&!form.use_rag){setError('指定必需参数时，必须启用知识库依据。');return;}
    void action(()=>api.createAgentRun({...form,goal:form.goal.trim(),required_facts:parameters.map(parameter=>({product_model:requiredModel.trim(),parameter})),source_urls:form.mode==='research'?sourceUrls.split(/\n+/).map(item=>item.trim()).filter(Boolean):[]}));};
  const openDraft=()=>{if(run?.draft_id)onOpenDraft?.(run.draft_id,run.selected_topic_id??null,run.id);};
  const running=Boolean(run&&['pending','running'].includes(run.status));
  const stage=run?run.status==='approved'?3:['awaiting_review','rejected'].includes(run.status)?2:run.steps.some(item=>item.key==='retrieve_context'&&item.status==='completed')?1:0:0;
  const issues=(Array.isArray(run?.evaluation?.issues)?run?.evaluation?.issues:[]) as Array<{message?:string;level?:string;card_page?:number}>;
  const evidence=(run?.result_json?.rag_context||{}) as {hits?:RagSearchHit[];knowledge_base_name?:string;required_facts?:Array<{product_model:string;parameter:string}>;answerability?:string};
  const currentReview=run?.result_json?.review as {decision?:string;note?:string;at?:string}|undefined;
  const reviewHistory=(run?.result_json?.review_history||[]) as Array<{decision?:string;note?:string;reason?:string}>;
  const brief=run?.result_json?.brief as BusinessBrief|undefined;
  const editChanged=Boolean(run?.result_json?.review_invalidated||run?.result_json?.evaluation_stale);
  return <div className="task-page"><div className="page-header compact-page-heading"><div><h1>从品牌资料，到可交付内容。</h1><p>选好品牌和任务模板，提交内容目标。生成后进入人工审核。</p></div></div>
    {(error||modelsError)&&<div className="feedback error" role="alert">{error||modelsError}</div>}{pollError&&<div className="notice-strip" role="status">{pollError}</div>}
    <div className="task-columns"><section className="panel task-form">{showComposer?<><div className="section-heading"><h2>你想写什么？</h2>{run&&<button className="text-action" onClick={()=>setShowComposer(false)}>返回当前任务</button>}</div><div className="form-group"><label htmlFor="task-brand">为哪个品牌创作</label><select id="task-brand" value={form.brand_profile_id||''} onChange={event=>selectBrand(Number(event.target.value)||null)}><option value="">暂不使用品牌档案</option>{brands.filter(b=>b.is_active).map(b=><option key={b.id} value={b.id}>{b.name} · v{b.version}</option>)}</select><button className="text-action" onClick={()=>onNavigate('brands')}>管理品牌档案 ↗</button></div>
      <div className="workflow-choices" aria-label="内容任务模板">{workflows.map(w=><button className="workflow-choice" key={w.key} aria-pressed={form.workflow_key===w.key} onClick={()=>setForm({...form,workflow_key:w.key,use_rag:true})}><strong>{w.name}</strong></button>)}</div>
      {selectedWorkflow&&<details className="calm-details task-material-hint"><summary>这个流程需要哪些资料？</summary><p className="subtle">{selectedWorkflow.required_materials.join('、')}。交付为图文稿和卡片，发布由你在官方后台完成。</p></details>}
      {selectedBrand&&<p className="subtle">已应用品牌第 {selectedBrand.version} 版要求{selectedBrand.data_policy==='local_only'?' · 仅本地摘录':''}</p>}
      <div className="form-group"><label htmlFor="task-goal">本次内容目标</label><textarea id="task-goal" maxLength={1000} className="goal-input" value={form.goal} onChange={event=>setForm({...form,goal:event.target.value})} placeholder="例如：根据产品说明，写一份给新用户的快速上手指南" rows={3}/></div>

      <details className="calm-details"><summary>必须有依据的产品参数（可选）</summary><p className="subtle">填写后，缺少任一项已核验参数就停止生成。型号和参数名需与核验笔记一致；留空只检索相关资料，不能保证目标中的所有问题都有答案。</p><div className="form-row"><div className="form-group"><label htmlFor="task-required-model">品牌及产品型号</label><input id="task-required-model" maxLength={200} value={requiredModel} onChange={event=>setRequiredModel(event.target.value)} placeholder="例如：合成星桥 XP-24"/></div><div className="form-group"><label htmlFor="task-required-parameters">必需参数 · 每行一项，最多 10 项</label><textarea id="task-required-parameters" rows={3} value={requiredParameters} onChange={event=>setRequiredParameters(event.target.value)} placeholder={'额定电压\n额定流量'}/></div></div></details>
      <div className="form-row"><div className="form-group"><label htmlFor="task-kb">使用哪份知识库</label><select id="task-kb" disabled={Boolean(selectedBrand)} value={form.knowledge_base_id||''} onChange={event=>setForm({...form,knowledge_base_id:Number(event.target.value)||null})}><option value="" disabled>选择知识库</option>{knowledgeBases.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="form-group"><label htmlFor="task-provider">生成方式</label><select id="task-provider" disabled={selectedBrand?.data_policy==='local_only'} value={form.provider} onChange={event=>setForm({...form,provider:event.target.value})}>{models.filter(item=>selectedBrand?.data_policy!=='local_only'||item.provider==='local').map(item=><option key={item.provider} value={item.provider}>{item.provider==='local'?'本地摘录 · 无需密钥':item.model||item.provider}</option>)}</select></div></div>
      <p className="task-model-hint">{form.provider==='local'?'本地模式用规则整理和摘录资料。选择已配置的在线模型可生成更自然的正文。':'本次会将目标和检索到的资料发送给所选模型。'} <button className="text-action" onClick={()=>onNavigate('connections')}>管理模型</button></p>
      <details className="calm-details"><summary>更多要求 · 受众、观点与参考链接</summary><div className="form-group"><label htmlFor="task-audience">写给谁看</label><input id="task-audience" value={form.target_audience||''} onChange={event=>setForm({...form,target_audience:event.target.value})} placeholder="例如：第一次使用产品的新用户"/></div><div className="form-group"><label htmlFor="task-viewpoint">特别要求</label><textarea id="task-viewpoint" value={form.viewpoint||''} onChange={event=>setForm({...form,viewpoint:event.target.value})} rows={2}/></div><div className="form-group"><label htmlFor="task-case">可使用的真实案例（可选）</label><textarea id="task-case" value={form.personal_case||''} onChange={event=>setForm({...form,personal_case:event.target.value})} rows={2}/></div><label className="inline-choice"><input type="checkbox" checked={form.mode==='research'} onChange={event=>setForm({...form,mode:event.target.checked?'research':'inspiration'})}/>结合指定网页资料</label>{form.mode==='research'&&<div className="form-group"><label htmlFor="task-links">参考链接 · 每行一个</label><textarea id="task-links" value={sourceUrls} onChange={event=>setSourceUrls(event.target.value)} rows={3}/><p className="subtle">读取你提供的链接，不会自动搜索整个互联网。</p></div>}<label className="inline-choice"><input type="checkbox" checked={Boolean(form.use_rag)} disabled={Boolean(form.brand_profile_id||form.workflow_key)} onChange={event=>setForm({...form,use_rag:event.target.checked})}/>使用知识库作为事实依据</label><label className="inline-choice"><input type="checkbox" checked={Boolean(form.auto_score)} onChange={event=>setForm({...form,auto_score:event.target.checked})}/>额外评估选题价值（正文质量检查始终执行）</label><div className="form-group"><label htmlFor="task-evidence-count">最多采用的证据片段</label><select id="task-evidence-count" value={form.rag_top_k||5} onChange={event=>setForm({...form,rag_top_k:Number(event.target.value)})}><option value={3}>3 条</option><option value={5}>5 条</option><option value={8}>8 条</option></select></div></details>
      <div className="form-actions"><button className="btn btn-primary" onClick={start} disabled={!canWrite||!briefReady||loading||!form.goal.trim()||!models.length||Boolean(form.use_rag&&!form.knowledge_base_id)}>{loading?'正在创建…':'生成内容草稿 →'}</button><button className="text-action" onClick={()=>onNavigate('knowledge')}>先补充资料</button></div></>:<div className="section-heading"><div><h2>{running?'正在处理你的内容':'当前任务'}</h2><p className="subtle">{run?.goal||'正在读取指定任务…'}</p></div><button className="btn" disabled={loading} onClick={()=>onNavigate('agent')}>新建内容</button></div>}</section>
      <aside className="panel task-history"><h2>最近任务</h2>{historyError&&<p className="feedback error">{historyError}<button className="text-action" onClick={loadHistory}>重新读取</button></p>}{!history.length&&!historyError?<p className="empty">新任务会保存在这里，可以随时回来继续。</p>:history.map(item=><button className="recent-work" key={item.id} disabled={loading} onClick={()=>onNavigate(`agent?run=${item.id}`)}><span className={`status-dot status-${item.status}`}/><div><strong>{item.goal}</strong><small>#{item.id} · {labels[item.status]||item.status}</small></div></button>)}</aside></div>
    {run&&<section className="panel task-result"><div className="result-heading"><div><span className="eyebrow">内容任务 #{run.id}</span><h2>{labels[run.status]||run.status}</h2><p className="subtle">{run.goal}</p></div>{run.draft_id&&<button className="btn btn-primary" disabled={loading||running} onClick={openDraft}>{run.status==='approved'?'打开交付内容':'编辑这份稿件'} →</button>}</div>
      {brief&&<div className="brand-task-context"><strong>{brief.profile?.name||'未指定品牌'}{brief.profile?` · v${brief.profile.version}`:''} / {brief.workflow.name}</strong><p>本任务保存创建时的品牌要求，后续档案修改不影响这份快照。</p></div>}
      {run.status==='approved'&&<div className="delivery-actions"><button className="btn btn-primary" disabled={downloading||loading} onClick={()=>void downloadDelivery()}>{downloading?'正在核对交付版本…':'下载审核交付清单'}</button><button className="btn" onClick={()=>onNavigate('metrics')}>发布后记录效果</button><p className="subtle">清单包含正文、出处与审核版本。图片素材请打开交付内容导出。</p></div>}
      <div className="task-stage-row">{['准备资料','生成与检查','人工审核'].map((text,index)=><div className={`task-stage ${stage>index?'done':stage===index?'current':''}`} key={text}><b>0{index+1}</b>{text}</div>)}</div>
      {run.error_message&&<div className="feedback error" role="alert">{run.error_message}</div>}
      <div className="form-actions">{running&&<button className="btn" disabled={!canWrite||loading} onClick={()=>void action(()=>workbench.cancel(run.id))}>停止任务</button>}{run.status==='failed'&&<><button className="btn btn-primary" disabled={!canWrite||loading} onClick={()=>void action(()=>api.retryAgentRun(run.id))}>从失败处重试</button><button className="text-action" onClick={()=>onNavigate('knowledge')}>检查资料</button></>}{run.status==='rejected'&&<><button className="btn btn-primary" disabled={!canWrite||loading} onClick={openDraft}>修改原稿</button><button className="btn" disabled={!canWrite||loading} onClick={()=>void action(()=>workbench.submitReview(run.id))}>修改后重新送审</button></>}</div>
      {run.draft&&<><div className="section-heading" style={{marginTop:22}}><h3>当前草稿</h3><span className="subtle">{run.cards.length} 张卡片 · {run.draft.model_provider||run.provider}</span></div><div className="task-body">{run.draft.body_text}</div></>}
      {run.status==='awaiting_review'&&<div className="task-review" style={{marginTop:22}}><h3>检查来源与内容，再作决定</h3><p>{issues.length?`质量检查提出 ${issues.length} 项建议，请展开下方详情查看。`:'请核对内容是否准确，引用是否支持对应结论。'} 通过后仍需手动导出和发布。</p><label htmlFor="review-note" className="subtle">审核备注</label><textarea id="review-note" value={reviewNote} onChange={event=>setReviewNote(event.target.value)} placeholder="记录已核实的内容，或需要修改的问题" rows={2}/><div className="form-actions"><button className="btn btn-primary" disabled={!canReview||loading} onClick={()=>void action(()=>workbench.review(run.id,'approve',reviewNote))}>审核通过</button><button className="btn" disabled={!canReview||loading} onClick={()=>void action(()=>workbench.review(run.id,'reject',reviewNote))}>退回修改</button></div></div>}
      {currentReview&&<div className="notice-strip" style={{marginTop:18}}><strong>{currentReview.decision==='approve'?'审核结论：通过':'审核结论：退回修改'}</strong><p>{currentReview.note||'本次未填写审核备注。'}</p>{currentReview.at&&<small>{new Date(currentReview.at.endsWith('Z')?currentReview.at:`${currentReview.at}Z`).toLocaleString()}</small>}</div>}
      {editChanged&&<p className="notice-strip">{run.status==='approved'?'当前版本已人工审核；历史评分对应修改前内容，不能用于本版质量判断。':'稿件已修改，请基于当前版本重新检查。此前评分不能代替这次审核。'}</p>}
      {issues.length>0&&<details className="calm-details"><summary>质量建议 · {issues.length} 项{run.evaluation_score!=null?` · 本次评分 ${run.evaluation_score}/100`:''}</summary><ul>{issues.map((item,index)=><li key={index} className="subtle">{item.card_page?`第 ${item.card_page} 页：`:''}{item.message}</li>)}</ul><p className="subtle">模型自评分用于辅助检查，不是客户验收结果。</p></details>}
      <details className="calm-details"><summary>查看依据 · {(evidence.hits||[]).length} 条检索片段</summary><p className="subtle">{evidence.knowledge_base_name||'本任务资料'} · 以下为生成时保存的依据。核验笔记可查看当前状态；审核和正式交付会再次检查有效性。</p>{Boolean(evidence.required_facts?.length)&&<p className="subtle">本次必需参数：{evidence.required_facts!.map(item=>`${item.product_model} / ${item.parameter}`).join('；')}。已找到依据仍须逐项核对生成正文。</p>}{(evidence.hits||[]).map(hit=><div key={hit.chunk_id} className="task-citation"><h4>{hit.title} <small>来源片段 #{hit.chunk_id}</small></h4><p>{hit.content}</p><EvidenceProvenance metadata={hit.metadata||{}} scope={{workspace_id:hit.workspace_id,knowledge_base_id:hit.knowledge_base_id}} onOpenEvidence={onOpenEvidence}/></div>)}</details>
      <details className="calm-details"><summary>执行详情与审核历史</summary><p className="subtle">本次模型：{run.provider} · 已完成 {run.steps.filter(step=>['completed','skipped'].includes(step.status)).length}/{run.steps.length} 步</p><ol className="task-steps">{run.steps.map(step=><li key={step.id}><span>{step.label}</span><span>{labels[step.status]||step.status} {step.duration_ms!=null&&<small>· {(step.duration_ms/1000).toFixed(1)} 秒</small>}</span></li>)}</ol>{reviewHistory.map((item,index)=><p className="subtle" key={index}>{item.decision==='approve'?'通过':'退回'} · {item.note||item.reason||'未填写备注'}</p>)}</details>
      <ModelTraceDetails key={run.id} runId={run.id} updatedAt={run.updated_at} revision={`${run.status}:${run.current_step}`} steps={run.steps}/>
    </section>}
  </div>;
}
