import { useState } from 'react';
import { SaasSession, saasApi } from '../api/saas';

export default function AuthPage({session,onAuthenticated}:{session:SaasSession;onAuthenticated:(session:SaasSession)=>void}) {
  const invite=new URLSearchParams(window.location.search).get('invite')||'';
  const [register,setRegister]=useState(Boolean(invite));
  const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [organization,setOrganization]=useState('');
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const result=register?await saasApi.register({name:name.trim(),email:email.trim(),password,organization_name:organization.trim(),...(invite?{invite_token:invite}:{})}):await saasApi.login(email.trim(),password);setPassword('');if(register&&invite)window.history.replaceState(null,'',window.location.pathname);onAuthenticated(result);}catch(e){setError(e instanceof Error?e.message:'暂时无法登录，请稍后重试');}finally{setBusy(false);}};
  return <main className="auth-layout"><section className="auth-story"><a className="auth-brand" href="/">知源<span>团队知识与内容工作台</span></a><div><span className="eyebrow">KNOWLEDGE, WITH A SOURCE.</span><h1>让每一份内容，<br/>都有可靠的来处。</h1><p>把分散的产品资料变成团队可用的知识。核对来源、协作审核，再生成有据可查的内容。</p><div className="auth-story-flow"><span>整理资料</span><i>→</i><span>核验入库</span><i>→</i><span>引用与审核</span></div></div><small>为小团队的日常知识工作而设计</small></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><span className="saas-kicker">欢迎来到知源</span><h2>{register?invite?'加入受邀团队':'创建你的工作空间':'登录工作空间'}</h2><p className="subtle">{register?invite?'使用收到邀请的邮箱注册，完成后确认加入团队。':'注册后即可整理资料并邀请团队成员。':'继续处理团队的资料、核验与内容。'}</p>{invite&&<div className="notice-strip">检测到团队邀请。请使用受邀邮箱登录或注册。</div>}{error&&<div className="feedback error" role="alert">{error}</div>}<fieldset disabled={busy}>{register&&<div className="form-group"><label htmlFor="auth-name">你的称呼</label><input id="auth-name" autoComplete="name" maxLength={100} required value={name} onChange={e=>setName(e.target.value)}/></div>}<div className="form-group"><label htmlFor="auth-email">邮箱</label><input id="auth-email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="form-group"><label htmlFor="auth-password">密码{register?'（至少 12 个字符）':''}</label><input id="auth-password" type="password" autoComplete={register?'new-password':'current-password'} minLength={register?12:1} maxLength={256} required value={password} onChange={e=>setPassword(e.target.value)}/></div>{register&&!invite&&<div className="form-group"><label htmlFor="auth-org">团队 / 组织名称</label><input id="auth-org" maxLength={100} required value={organization} onChange={e=>setOrganization(e.target.value)} placeholder="例如：星河产品团队"/></div>}<button className="btn btn-primary auth-submit" type="submit">{busy?'正在处理…':register?'创建账号':'登录'}</button></fieldset>{(session.allow_registration||invite)&&<p className="auth-switch">{register?'已有账号？':'还没有账号？'}<button className="btn btn-link" type="button" disabled={busy} onClick={()=>{setRegister(!register);setError('');}}>{register?'登录':'创建账号'}</button></p>}<p className="auth-footer">本阶段提供小团队试点功能；升级申请不触发付款。</p></form></section></main>;
}
